### ISSUE TITLE
Error  on npm run cordova-android in windows

### ISSUE THREAD

**Issue by gedeoni** [sts-ryan-holton/nuxt-cordova-app#6]
After running npm running cordova-android on windows  I get the error below 
![image](https://user-images.githubusercontent.com/49534208/86492629-0ae4ae80-bd6f-11ea-9f1c-29ec1a9303b2.png)

**Comment by sts-ryan-holton** [comment]
@gedeoni I wonder whether this is a Windows specific issue related to the [replace](https://www.npmjs.com/package/replace) package? Could you try listing all the commands in order that you ran?
