### ISSUE TITLE
fresh installation -> "cordova prepare" not working 

### ISSUE THREAD

**Issue by dburucu** [sts-ryan-holton/nuxt-cordova-app#7]
make dir "www" under "cordova" to run "cordova prepare" without error.

**Comment by sts-ryan-holton** [comment]
@dburucu Yes, a directory called `www` will need to be made. However, this is already listed in the README.md -> https://github.com/sts-ryan-holton/nuxt-cordova-app#installation

> Note: if cordova prepare fails, check that the cordova/www directory exists, if it doesn't create it.
